# Generated by Django 2.0.3 on 2018-03-14 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardPurchaseBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_on', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('notes', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SingleCardPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expansion', models.CharField(max_length=100)),
                ('tcgplayer_card_id', models.PositiveIntegerField(blank=True, null=True)),
                ('buy_price', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('lowest_listing_at_buy', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('market_price_at_buy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sold_on', models.DateTimeField(blank=True, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('market_price_at_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lowest_listing_at_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Buy.CardPurchaseBlock')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent_modifier', models.DecimalField(decimal_places=1, max_digits=4)),
                ('list_for_sale', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bearer', models.CharField(blank=True, default='', max_length=1000)),
                ('expires', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cardpurchaseblock',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Buy.Seller'),
        ),
    ]
