# Generated by Django 2.0.3 on 2018-04-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0002_standardset'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlecardpurchase',
            name='initial_sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
