# Generated by Django 2.0.3 on 2018-04-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0004_singlecardpurchase_lowest_direct_at_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpurchaseblock',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=20),
        ),
    ]
