# Generated by Django 2.0.3 on 2018-05-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0005_cardpurchaseblock_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCheckDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_check', models.DateTimeField()),
                ('last_sale_id', models.CharField(max_length=25)),
            ],
        ),
    ]
