# Generated by Django 2.0.3 on 2018-06-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0007_singlecardpurchase_lowest_direct_at_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlecardpurchase',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
