# Generated by Django 2.0.3 on 2018-07-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0009_auto_20180613_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='UntrackedCardSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expansion', models.CharField(max_length=100)),
                ('tcgplayer_card_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sold_on', models.DateTimeField(blank=True, null=True)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('market_price_at_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lowest_listing_at_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lowest_direct_at_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('in_house_sale', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='singlecardpurchase',
            name='in_house_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
